version: '3'

services:
  tooljet:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:latest
    container_name: tooljet
    restart: unless-stopped
    env_file: .env
    ports:
      - 8200:80
    depends_on:
      - postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod

  postgres:
    image: postgres:15.4
    container_name: tooljet-db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
