version: '3.3'

services:

    tooljet:
        image: tooljet/try:latest    
        container_name: tooljet
        restart: unless-stopped
        ports:
            - '8200:80'
        volumes:
            - ./tooljet_data:/var/lib/postgresql/13/main
